### ISSUE TITLE
oof...

### ISSUE THREAD

**Issue by jaylac2000** [TwistedAsylumMC/ChunkBorders#2]
PocketMine-MP Crash Dump Fri Jun 19 22:35:08 UTC 2020

Error: Call to a member function sendBlocks() on null
File: plugins/ChunkBorders_dev-2.phar/src/twisted/chunkborders/ChunkBorders
Line: 79
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: ChunkBorders v1.0.0

Code:
[70] 	/**
[71] 	 * Removes the current chunk border from the provided Player.
[72] 	 *
[73] 	 * @param Player $player
[74] 	 */
[75] 	public function removeChunkBorderFrom(Player $player) : void{
[76] 		$tilePos = $this->viewers[$player->getId()] ?? null;
[77] 		if($tilePos !== null){
[78] 			$this->sendFakeBlock($player, $tilePos, Block::get(Block::STRUCTURE_BLOCK));
[79] 			$tilePos->getLevel()->sendBlocks([$player], [$tilePos]);
[80] 		}
[81] 		unset($this->viewers[$player->getId()]);
[82] 	}
[83] 
[84] 	/**
[85] 	 * Send a fake block to a specific player
[86] 	 *  rather than the whole server.
[87] 	 *
[88] 	 * @param Player  $player
[89] 	 * @param Vector3 $position

Backtrace:
#0 plugins/ChunkBorders_dev-2.phar/src/twisted/chunkborders/ChunkBorders(109): twisted\chunkborders\ChunkBorders->removeChunkBorderFrom(object kielking\ApolloMCPECore\SubPlugins\NameSpaceRemover\CustomPlayer)
#1 plugins/ChunkBorders_dev-2.phar/src/twisted/chunkborders/EventListener(35): twisted\chunkborders\ChunkBorders->updateChunkBordersFor(object kielking\ApolloMCPECore\SubPlugins\NameSpaceRemover\CustomPlayer)
#2 src/pocketmine/scheduler/ClosureTask(61): twisted\chunkborders\EventListener->twisted\chunkborders\{closure}(integer 23703)
#3 src/pocketmine/scheduler/TaskHandler(134): pocketmine\scheduler\ClosureTask->onRun(integer 23703)
#4 src/pocketmine/scheduler/TaskScheduler(176): pocketmine\scheduler\TaskHandler->run(integer 23703)
#5 src/pocketmine/plugin/PluginManager(654): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 23703)
#6 src/pocketmine/Server(2388): pocketmine\plugin\PluginManager->tickSchedulers(integer 23703)
#7 src/pocketmine/Server(2151): pocketmine\Server->tick()
#8 src/pocketmine/Server(1991): pocketmine\Server->tickProcessor()
#9 src/pocketmine/Server(1585): pocketmine\Server->start()
#10 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
#11 src/pocketmine/PocketMine(296): pocketmine\server()
#12 (11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by jaylac2000** [comment]
nothing has been done... so i reported again - #3

**Comment by jaylac2000** [comment]
nvm this is different code...

**Comment by TwistedAsylumMC** [comment]
Closing due to duplicate
